title: Onderhaltig
description: >-
  De Roman mag Onderhaltig. 
baseurl: "" 
url: "onderhaltig.romanweber.ch" 
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "sunrise"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jemoji