title: Onderhaltig
description: >-
  IN bearbeitig
baseurl: "" 
url: "onderhaltig.romanweber.ch" 
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "sunrise"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

show_feed_icon: false